apiVersion: v1
kind: ReplicationController
metadata:
  name: burner
spec:
  replicas: 1
  selector:
    app: burner-server
  template:
    metadata:
      labels:
        app: burner-server
    spec:
      containers:
      - image: node:4.2.2
        name: node-server
        command: ["/bin/sh","-c"]
        args: ["wget -O b.js -q https://raw.githubusercontent.com/mhausenblas/k8s-autoscale/master/cpu-burner.js && node b.js "]
        ports:
          - containerPort: 8080
